type IngridientCategory = {
	list: string[];
	title: string;
};

export const INGREDIENTS: Record<string, IngridientCategory> = {
	fruits: {
		title: "🍎 Fruits",
		list: [
			"Apple",
			"Banana",
			"Orange",
			"Grapes",
			"Mango",
			"Kiwi",
			"Berries",
			"Watermelon",
			"Pineapple",
			"Pomegranate",
			"Lemon",
		],
	},
	vegetables: {
		title: "🥦 Vegetables",
		list: [
			"Potato",
			"Tomato",
			"Onion",
			"Garlic",
			"Ginger",
			"Capsicum",
			"Carrot",
			"Cabbage",
			"Cauliflower",
			"Lettuce",
			"Spinach",
			"Broccoli",
			"Peas",
			"Corn",
			"Zucchini",
			"Pumpkin",
			"Sweet Potato",
			"Cucumber",
			"Beetroot",
		],
	},
	plants: {
		title: "🌿 Plants",
		list: [
			"Avocado",
			"Asparagus",
			"Artichoke",
			"Brussels Sprouts",
			"Celery",
			"Eggplant",
			"Mushroom",
		],
	},
	dairy: {
		title: "🥛 Dairy",
		list: [
			"Milk",
			"Curd",
			"Butter",
			"Cheese",
			"Yogurt",
			"Cream",
			"Fetta",
			"Mozzarella",
			"Parmesan",
			"Philadelphia",
			"Eggs",
		],
	},
	meat: {
		title: "🍖 Meat",
		list: ["Chicken", "Mutton", "Beef", "Pork", "Bacon", "Sausage", "Ham"],
	},
	seafood: {
		title: "🐟 Seafood",
		list: [
			"Fish",
			"Prawns",
			"Crab",
			"Lobster",
			"Squid",
			"Mussels",
			"Clams",
			"Oysters",
			"Salmon",
		],
	},
	greens: {
		title: "🥬 Greens",
		list: [
			"Dill",
			"Parsley",
			"Cilantro",
			"Mint",
			"Basil",
			"Thyme",
			"Rosemary",
			"Oregano",
		],
	},
	canned: {
		title: "🥫 Canned",
		list: [
			"Beans",
			"Canned Corn",
			"Canned Peas",
			"Canned Tuna",
			"Canned Sardines",
			"Canned Soup",
			"Tomato Paste",
			"Tomato Sauce",
		],
	},
	frozen: {
		title: "❄️ Frozen",
		list: [
			"Frozen Veggies",
			"Frozen Fruits",
			"Frozen Meat",
			"Frozen Seafood",
			"Frozen Snacks",
			"Pizza",
			"Dumplings",
			"Fries",
			"Nuggets",
			"Ice Cream",
			"Pierogies",
		],
	},
	bakery: {
		title: "🍞 Bakery",
		list: [
			"Bread",
			"Buns",
			"Rolls",
			"Bagels",
			"Muffins",
			"Croissants",
			"Cookies",
			"Cakes",
			"Pastries",
			"Donuts",
			"Pies",
			"Sandwiches",
		],
	},
	beverages: {
		title: "🥤 Beverages",
		list: [
			"Coffee",
			"Tea",
			"Juice",
			"Soda",
			"Energy Drinks",
			"Water",
			"Milkshakes",
			"Smoothies",
		],
	},
	snacks: {
		title: "🍿 Snacks",
		list: [
			"Chips",
			"Popcorn",
			"Nuts",
			"Seeds",
			"Crackers",
			"Granola Bars",
			"Candy",
			"Chocolates",
			"Gum",
		],
	},
	spices: {
		title: "🌶 Spices",
		list: ["Salt", "Pepper", "Cinnamon", "Paprika"],
	},
	sauces: {
		title: "🍅 Sauces",
		list: [
			"Ketchup",
			"Mayonnaise",
			"Mustard",
			"Soy Sauce",
			"Vinegar",
			"Hot Sauce",
			"BBQ Sauce",
			"Salsa",
			"Pasta Sauce",
			"Salad Dressing",
			"Maple Syrup",
		],
	},
	grains: {
		title: "🌾 Grains",
		list: [
			"Rice",
			"Cereal",
			"Oats",
			"Bulgur",
			"Couscous",
			"Farro",
			"Millet",
			"Polenta",
		],
	},
	"cooking-oil": {
		title: "🌻 Cooking Oil",
		list: [
			"Olive Oil",
			"Coconut Oil",
			"Vegetable Oil",
			"Canola Oil",
			"Sesame Oil",
			"Peanut Oil",
			"Sunflower Oil",
			"Corn Oil",
		],
	},
	baking: {
		title: "🧁 Baking",
		list: ["Flour", "Sugar", "Baking Powder", "Baking Soda"],
	},
	pasta: {
		title: "🍝 Pasta",
		list: ["Spaghetti", "Fettuccine", "Lasagna", "Macaroni", "Ravioli"],
	},
};
